{% set name = "pynecone" %}
{% set version = "0.1.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pynecone-{{ version }}.tar.gz
  sha256: 04c316d59833e64cf479203fcdd249eae8f58bb41218c59255f1563b0ce9e96c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - cloudpickle >=2.2.1,<3.0.0
    - fastapi >=0.96.0,<0.97.0
    - gunicorn >=20.1.0,<21.0.0
    - httpx >=0.23.0,<0.24.0
    - jinja2 >=3.1.2,<4.0.0
    - nodejs >=16.8.0
    - plotly >=5.13.0,<6.0.0
    - psutil >=5.9.4,<6.0.0
    - pydantic >=1.10.2,<2.0.0
    - python >={{ python_min }},<4.0
    - python-dotenv >=0.13.0,<0.14.0
    - python-multipart >=0.0.5,<0.0.6
    - python-socketio >=5.7.0,<6.0.0
    - redis-py >=4.3.5,<5.0.0
    - rich >=13.0.0,<14.0.0
    - sqlmodel >=0.0.8,<0.0.9
    - starlette-admin >=0.9.0,<0.11.0
    - typer ==0.4.2
    - unzip
    - uvicorn >=0.20.0,<0.21.0
    - watchdog >=2.3.1,<3.0.0
    - websockets >=10.4,<11.0

test:
  imports:
    - pynecone
  commands:
    - pip list
    # - pip check
    - mkdir test_app;cd test_app;pc init;ls
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pynecone.io
  summary: Web apps in pure Python.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Alek99
    - goanpeca
